# Generated by Django 3.1.5 on 2021-01-21 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('code_validation', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Biens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=35)),
                ('statuts', models.BooleanField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomGroupe', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Type_Biens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameType', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='temp_occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetimedebut', models.DateTimeField()),
                ('datetimefin', models.DateTimeField()),
                ('validertemps', models.BooleanField()),
                ('biens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Biens_TempsOcc', to='fikor_api.biens')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_TempsOcc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.BooleanField()),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Groupe_Role', to='fikor_api.groupe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_Role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='biens',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Groupe_Biens', to='fikor_api.groupe'),
        ),
        migrations.AddField(
            model_name='biens',
            name='type_Biens',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Type_Biens', to='fikor_api.type_biens'),
        ),
        migrations.AddField(
            model_name='biens',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_Biens', to=settings.AUTH_USER_MODEL),
        ),
    ]
